//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Connections
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string FIO { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<long> Passport { get; set; }
        public Nullable<long> Bank { get; set; }
        public Nullable<int> Family { get; set; }
    
        public virtual Family Family1 { get; set; }
    }
}
