//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Connections
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialType
    {
        public MaterialType()
        {
            this.Materials = new HashSet<Materials>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> Brak { get; set; }
    
        public virtual ICollection<Materials> Materials { get; set; }
    }
}
