//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Connections
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        public int Id { get; set; }
        public int IdMaerialType { get; set; }
        public Nullable<double> MaterialUnitPrice { get; set; }
        public Nullable<int> KolvoNaSklade { get; set; }
        public Nullable<int> MinCount { get; set; }
        public Nullable<int> CountInUpakovka { get; set; }
        public int IdUnit { get; set; }
    
        public virtual MaterialType MaterialType { get; set; }
        public virtual UnitType UnitType { get; set; }
    }
}
