//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Connections
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlmazEntities : DbContext
    {
        public AlmazEntities()
            : base("name=AlmazEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Employee> Employee { get; set; }
        public DbSet<Family> Family { get; set; }
        public DbSet<MaterialName> MaterialName { get; set; }
        public DbSet<Materials> Materials { get; set; }
        public DbSet<MaterialType> MaterialType { get; set; }
        public DbSet<Partners> Partners { get; set; }
        public DbSet<PartnersType> PartnersType { get; set; }
        public DbSet<ProductType> ProductType { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<UnitType> UnitType { get; set; }
        public DbSet<Products> Products { get; set; }
    }
}
