//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Connections
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        public int Id { get; set; }
        public int Id_type { get; set; }
        public string CompanyName { get; set; }
        public Nullable<long> INN { get; set; }
        public string FIO { get; set; }
        public Nullable<int> Tel { get; set; }
        public string Email { get; set; }
        public string Logo { get; set; }
    
        public virtual PartnersType PartnersType { get; set; }
    }
}
