//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Connections
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int Articule { get; set; }
        public int IdProductType { get; set; }
        public string ProductName { get; set; }
        public Nullable<double> MinimalPrice { get; set; }
        public Nullable<double> RulonWidth { get; set; }
    
        public virtual ProductType ProductType { get; set; }
    }
}
